import FunctionContainer from '@/components/FunctionContainer'
import RandomBytes from '@/components/web3js/utils/RandomBytes'
import { Stack, Typography } from '@mui/joy'

export default async function Web3JsFunctionPage() {
    return (
        <Stack
            direction={{ xs: 'column', md: 'column' }}
            sx={{
                height: '100%',
                width: '100%',
            }}
            spacing={2}
        >
            <Typography level="h1">RandomBytes</Typography>
            <Typography level="h2">The RandomBytes function.</Typography>
            <Typography level="body-md">
              The <strong>randomBytes</strong> function is a utility method provided by the <strong>web3.utils</strong> module that generates a
               random byte array of a specified size. The function returns a <strong>Uint8Array</strong> containing random 
               bytes, which can be used for various purposes such as generating random numbers, creating 
               cryptographic keys, or simulating random data.
            </Typography>
            <Typography level="body-md">
              The function takes a single parameter, <strong>size,</strong> which specifies the size of the random byte array 
              to be generated. The <strong>size</strong> parameter must be a positive integer.
            </Typography>
            <Typography level="body-md">
              The <strong>randomBytes</strong> function returns a <strong>Uint8Array</strong> containing <strong>size</strong> random bytes. The bytes are 
              generated using a cryptographically secure pseudorandom number generator, which ensures that 
              the generated bytes are truly random and unpredictable.
            </Typography>
            <Typography level="body-md">
              Here's an example of how the randomBytes function can be used:

                <pre>const randomBytes = web3.utils.randomBytes(32);</pre>
                <pre>console.log(randomBytes);</pre>
            </Typography>
            <Typography level="body-md">
              In this example, the <strong>randomBytes</strong> function is called with a size of 32, and it returns a 
              <strong>Uint8Array</strong> containing 32 random bytes. The resulting array is logged to the console, 
              showing the random bytes that were generated.
            </Typography>
            <Stack
                direction={{ xs: 'column', md: 'column' }}
                sx={{
                    height: '100%',
                    width: '100%',
                }}
                overflow={'scroll'}
                spacing={2}
            >
                <FunctionContainer title="web3.randomBytes" description="">
                    <RandomBytes />
                </FunctionContainer>
            </Stack>
        </Stack>
    )
}
