import FunctionContainer from '@/components/FunctionContainer'
import GetContractAddress from '@/components/viem/utils/Addresses/GetContractAddress'

import { Stack, Typography } from '@mui/joy'

export default async function Web3JsFunctionPage() {
  return (
    <Stack
      direction={{ xs: 'column', md: 'column' }}
      sx={{
        height: '100%',
        width: '100%',
      }}
      spacing={2}
    >
      <Typography level='h1'>GetContractAddress</Typography>
      <Typography level='h2'>The GetContractAddress function.</Typography>

      <Typography level='body-md'>
        The <strong>getContractAddress</strong> function retrieves the contract
        address generated by the CREATE or CREATE2 opcode after deploying a
        contract to the network. It takes various parameters, including the
        address the contract was deployed from, the nonce of the transaction
        that deployed the contract, and the opcode used for deployment
        (defaulting to CREATE). The function returns the contract address as a
        hex string.
      </Typography>

      <Typography level='body-md'>
        The function also has optional parameters for the bytecode and bytecode
        hash of the contract, which are only applicable for CREATE2 deployments.
        The <strong>salt</strong> parameter is also optional and can be any
        arbitrary value provided by the sender.
      </Typography>

      <Typography level='body-md'>
        Here's a summary of the parameters and their types:
        <ul>
          <li>
            <strong>from:</strong> Address (optional)
          </li>
          <li>
            <strong>nonce:</strong> Address (optional)
          </li>
          <li>
            <strong>opcode:</strong> "CREATE" | "CREATE2" (optional, default:
            "CREATE")
          </li>
          <li>
            <strong>bytecode:</strong> ByteArray | Hex (optional, only
            applicable for opcode: 'CREATE2')
          </li>
          <li>
            <strong>bytecodeHash:</strong> ByteArray | Hex (optional, only
            applicable for opcode: 'CREATE2')
          </li>
          <li>
            <strong>salt:</strong> ByteArray | Hex (optional)
          </li>
        </ul>
      </Typography>

      <Typography level='body-md'>
        The function returns a hex string representing the contract address.
      </Typography>

      <Stack
        direction={{ xs: 'column', md: 'column' }}
        sx={{
          height: '100%',
          width: '100%',
        }}
        overflow={'scroll'}
        spacing={2}
      >
        <FunctionContainer title='web3.getContractAddress' description=''>
          <GetContractAddress />
        </FunctionContainer>
      </Stack>
    </Stack>
  )
}
